export const site = {
  name: "Greenfields Flooring",
  tagline: "A family‑run flooring showroom in Lancing",
  phone: "01903 763687",
  email: "Greenfieldflooring@hotmail.com",
  address: {
    line1: "76 Manor Road",
    town: "Lancing",
    postcode: "BN15 0HD",
    country: "United Kingdom",
  },
  opening: [
    { day: "Mon", hours: "9:30am – 4:30pm" },
    { day: "Tue", hours: "9:30am – 4:30pm" },
    { day: "Wed", hours: "9:30am – 2:30pm" },
    { day: "Thu", hours: "9:30am – 4:30pm" },
    { day: "Fri", hours: "9:30am – 4:30pm" },
    { day: "Sat", hours: "9am – 1pm" },
    { day: "Sun", hours: "Closed" },
  ],
  socials: {
    facebook: "https://www.facebook.com/greenfieldsflooring",
    instagram: "https://www.instagram.com/greenfields_flooring_lancing/",
    checkatrade: "https://www.checkatrade.com/trades/greenfieldsflooring",
    googleReview: "https://search.google.com/local/writereview?placeid=ChIJWxHSoMqZdUgRij_ovUD4v1A"
  },
  services: [
    { title: "Carpets", desc: "Showroom ranges plus home selection with expert advice and fitting." },
    { title: "Vinyl & LVT", desc: "Practical, stylish solutions including luxury vinyl tile options." },
    { title: "Wood & Laminate", desc: "Hard‑wearing floors fitted beautifully for busy homes." },
    { title: "Natural Flooring", desc: "Sisal, coir, seagrass and other plant‑based fibres." },
    { title: "Safety & Commercial", desc: "Slip‑resistant, durable flooring for workplaces and public spaces." },
    { title: "Floor Preparation", desc: "Latexing, hardboarding and uplift of existing flooring." },
  ],
  reviews: [
    { name: "Steve Clark", quote: "Could not be happier with the service we received." },
    { name: "Ian Reading", quote: "Thrilled with the workmanship and final result — would highly recommend." },
    { name: "D Heritage", quote: "Amazing customer service. Great fitting and a competitive price." },
    { name: "Emma Rapson", quote: "Excellent carpet and fitting — so helpful in the shop." },
    { name: "Marielle Pemberton", quote: "Professional, reliable and always finish to a high standard." },
    { name: "Kay Norris", quote: "Very professional, polite and communicated with us when needed." }
  ],
  
  gallery: [
    "/gallery/photo-new.jpeg",
    "/gallery/photo-02.jpeg",
    "/gallery/photo-03.jpeg",
    "/gallery/photo-04.jpeg",
    "/gallery/photo-05.jpeg",
    "/gallery/photo-06.jpeg",
    "/gallery/photo-07.jpeg",
    "/gallery/photo-08.jpeg",
    "/gallery/photo-09.jpeg",
    "/gallery/photo-10.jpeg",
    "/gallery/photo-11.jpeg",
    "/gallery/photo-12.jpeg",
    "/gallery/photo-13.jpeg",
    "/gallery/photo-14.jpeg",
    "/gallery/photo-15.jpeg",
    "/gallery/photo-16.jpeg",
    "/gallery/photo-17.jpeg",
    "/gallery/photo-18.jpeg",
    "/gallery/photo-19.jpeg",
    "/gallery/photo-20.jpeg",
    "/gallery/photo-21.jpeg",
    "/gallery/photo-22.jpeg",
    "/gallery/photo-23.jpeg",
    "/gallery/photo-24.jpeg",
  ],
  proof: [
    { k: "65+ years", v: "Combined fitting experience" },
    { k: "Family‑run", v: "Generations of craftsmanship" },
    { k: "Free estimates", v: "Honest advice & clear pricing" },
  ],
};
